import { Patient, Doctor, Resource, Transaction, AuditEvent, Notification, SagaWorkflow } from '../types/index.js';

export class HospitalDatabase {
  public patients: Map<string, Patient> = new Map();
  public doctors: Map<string, Doctor> = new Map();
  public resources: Map<string, Resource> = new Map();
  public transactions: Map<string, Transaction> = new Map();
  public auditEvents: AuditEvent[] = [];
  public notifications: Notification[] = [];
  public sagas: Map<string, SagaWorkflow> = new Map();
  public idempotencyStore: Map<string, { txnId: string; response: any; timestamp: number }> = new Map();

  // Failure lab active simulation flags
  public chaosFlags = {
    serviceUnavailable: false,
    dbLockContention: false,
    networkTimeoutMs: 0,
    forceNextTxnFail: false,
    duplicateDropRate: 0,
  };

  constructor() {
    this.seedData();
  }

  public seedData() {
    // 10+ Doctors
    const doctorsList: Doctor[] = [
      {
        id: 'DOC-001',
        name: 'Dr. Sarah Williams',
        specialization: 'Critical Care & Pulmonology',
        department: 'ICU / Critical Care',
        availability: 'AVAILABLE',
        assignedPatientsCount: 3,
        activeEmergencyCount: 1,
        email: 's.williams@mediflow.org',
        phone: '+1 (555) 234-5678',
        rating: 4.9,
      },
      {
        id: 'DOC-002',
        name: 'Dr. Marcus Vance',
        specialization: 'Cardiothoracic Surgery',
        department: 'Surgical Operations',
        availability: 'IN_SURGERY',
        assignedPatientsCount: 2,
        activeEmergencyCount: 1,
        email: 'm.vance@mediflow.org',
        phone: '+1 (555) 345-6789',
        rating: 4.8,
      },
      {
        id: 'DOC-003',
        name: 'Dr. Elena Rostova',
        specialization: 'Emergency Trauma Medicine',
        department: 'Emergency Medicine',
        availability: 'AVAILABLE',
        assignedPatientsCount: 4,
        activeEmergencyCount: 2,
        email: 'e.rostova@mediflow.org',
        phone: '+1 (555) 456-7890',
        rating: 5.0,
      },
      {
        id: 'DOC-004',
        name: 'Dr. Arthur Chen',
        specialization: 'Neurocritical Care',
        department: 'Neurology',
        availability: 'ON_CALL',
        assignedPatientsCount: 2,
        activeEmergencyCount: 0,
        email: 'a.chen@mediflow.org',
        phone: '+1 (555) 567-8901',
        rating: 4.7,
      },
      {
        id: 'DOC-005',
        name: 'Dr. Priyanka Sharma',
        specialization: 'Nephrology & Dialysis',
        department: 'Renal Care',
        availability: 'AVAILABLE',
        assignedPatientsCount: 3,
        activeEmergencyCount: 0,
        email: 'p.sharma@mediflow.org',
        phone: '+1 (555) 678-9012',
        rating: 4.9,
      },
      {
        id: 'DOC-006',
        name: 'Dr. James Thornton',
        specialization: 'Orthopedic Trauma',
        department: 'Orthopedics',
        availability: 'AVAILABLE',
        assignedPatientsCount: 2,
        activeEmergencyCount: 0,
        email: 'j.thornton@mediflow.org',
        phone: '+1 (555) 789-0123',
        rating: 4.6,
      },
      {
        id: 'DOC-007',
        name: 'Dr. Sofia Rodriguez',
        specialization: 'Pediatric Intensive Care',
        department: 'Pediatrics',
        availability: 'AVAILABLE',
        assignedPatientsCount: 2,
        activeEmergencyCount: 0,
        email: 's.rodriguez@mediflow.org',
        phone: '+1 (555) 890-1234',
        rating: 4.9,
      },
      {
        id: 'DOC-008',
        name: 'Dr. Alexander Hayes',
        specialization: 'Anesthesiology & Perioperative Care',
        department: 'Anesthesiology',
        availability: 'IN_SURGERY',
        assignedPatientsCount: 1,
        activeEmergencyCount: 0,
        email: 'a.hayes@mediflow.org',
        phone: '+1 (555) 901-2345',
        rating: 4.8,
      },
      {
        id: 'DOC-009',
        name: 'Dr. Maya Patel',
        specialization: 'Medical Oncology',
        department: 'Oncology',
        availability: 'AVAILABLE',
        assignedPatientsCount: 3,
        activeEmergencyCount: 0,
        email: 'm.patel@mediflow.org',
        phone: '+1 (555) 012-3456',
        rating: 4.9,
      },
      {
        id: 'DOC-010',
        name: 'Dr. David Kim',
        specialization: 'Infectious Diseases',
        department: 'Internal Medicine',
        availability: 'ON_CALL',
        assignedPatientsCount: 2,
        activeEmergencyCount: 0,
        email: 'd.kim@mediflow.org',
        phone: '+1 (555) 123-4560',
        rating: 4.7,
      },
    ];

    doctorsList.forEach((doc) => this.doctors.set(doc.id, doc));

    // 35+ Resources
    const resourcesList: Resource[] = [
      // ICU Beds
      { id: 'BED-ICU-01', name: 'ICU Bed 01 (Negative Pressure)', type: 'BED_ICU', department: 'ICU', status: 'OCCUPIED', version: 14, assignedPatientId: 'PAT-1001', assignedPatientName: 'Johnathan Miller', lastModified: new Date(Date.now() - 3600000).toISOString(), specs: { monitor: 'Philips IntelliVue MX800', gasOutlet: 'Dual O2 + MedAir' } },
      { id: 'BED-ICU-02', name: 'ICU Bed 02 (Telemetry)', type: 'BED_ICU', department: 'ICU', status: 'AVAILABLE', version: 9, lastModified: new Date(Date.now() - 7200000).toISOString(), specs: { monitor: 'GE Carescape B850', gasOutlet: 'Dual O2' } },
      { id: 'BED-ICU-03', name: 'ICU Bed 03 (Cardiac)', type: 'BED_ICU', department: 'ICU', status: 'OCCUPIED', version: 21, assignedPatientId: 'PAT-1002', assignedPatientName: 'Emma Watson-Clarke', lastModified: new Date(Date.now() - 10800000).toISOString(), specs: { monitor: 'Mindray BeneVision N22', gasOutlet: 'Quad O2' } },
      { id: 'BED-ICU-04', name: 'ICU Bed 04 (Neuro)', type: 'BED_ICU', department: 'ICU', status: 'AVAILABLE', version: 5, lastModified: new Date(Date.now() - 14400000).toISOString(), specs: { monitor: 'Philips MX800', gasOutlet: 'Dual O2' } },
      { id: 'BED-ICU-05', name: 'ICU Bed 05 (Isolation)', type: 'BED_ICU', department: 'ICU', status: 'RESERVED', version: 18, assignedPatientId: 'PAT-1004', assignedPatientName: 'Carlos Ramirez', lastModified: new Date(Date.now() - 1800000).toISOString(), specs: { monitor: 'GE B850', gasOutlet: 'Dual O2 + Vacuum' } },
      { id: 'BED-ICU-06', name: 'ICU Bed 06 (General)', type: 'BED_ICU', department: 'ICU', status: 'AVAILABLE', version: 3, lastModified: new Date(Date.now() - 25000000).toISOString(), specs: { monitor: 'Mindray N19', gasOutlet: 'Dual O2' } },
      { id: 'BED-ICU-07', name: 'ICU Bed 07 (Pediatric PICU)', type: 'BED_ICU', department: 'PICU', status: 'AVAILABLE', version: 7, lastModified: new Date(Date.now() - 12000000).toISOString(), specs: { monitor: 'Philips MX550', gasOutlet: 'Dual O2' } },
      { id: 'BED-ICU-08', name: 'ICU Bed 08 (Burn Unit)', type: 'BED_ICU', department: 'ICU', status: 'AVAILABLE', version: 4, lastModified: new Date(Date.now() - 32000000).toISOString(), specs: { monitor: 'GE B850', gasOutlet: 'Fluid Bed Interface' } },

      // Emergency Trauma Bays
      { id: 'BED-ER-01', name: 'Trauma Bay 01 (Resuscitation)', type: 'BED_EMERGENCY', department: 'Emergency', status: 'OCCUPIED', version: 32, assignedPatientId: 'PAT-1003', assignedPatientName: 'Derrick Vance', lastModified: new Date(Date.now() - 500000).toISOString(), specs: { defib: 'Zoll R Series', suction: 'High Flow' } },
      { id: 'BED-ER-02', name: 'Trauma Bay 02 (Rapid Response)', type: 'BED_EMERGENCY', department: 'Emergency', status: 'AVAILABLE', version: 28, lastModified: new Date(Date.now() - 1200000).toISOString(), specs: { defib: 'Physio-Control Lifepak 15' } },
      { id: 'BED-ER-03', name: 'Emergency Bay 03', type: 'BED_EMERGENCY', department: 'Emergency', status: 'AVAILABLE', version: 15, lastModified: new Date(Date.now() - 4000000).toISOString() },
      { id: 'BED-ER-04', name: 'Emergency Bay 04', type: 'BED_EMERGENCY', department: 'Emergency', status: 'OCCUPIED', version: 19, assignedPatientId: 'PAT-1007', assignedPatientName: 'Sarah Jenkins', lastModified: new Date(Date.now() - 6000000).toISOString() },
      { id: 'BED-ER-05', name: 'Emergency Bay 05 (Fast Track)', type: 'BED_EMERGENCY', department: 'Emergency', status: 'AVAILABLE', version: 11, lastModified: new Date(Date.now() - 8000000).toISOString() },
      { id: 'BED-ER-06', name: 'Emergency Bay 06', type: 'BED_EMERGENCY', department: 'Emergency', status: 'AVAILABLE', version: 8, lastModified: new Date(Date.now() - 9500000).toISOString() },

      // General Ward Beds
      { id: 'BED-WRD-101', name: 'Ward Bed 101-A', type: 'BED_WARD', department: 'Cardiology Ward', status: 'OCCUPIED', version: 12, assignedPatientId: 'PAT-1005', assignedPatientName: 'Mei-Ling Zhang', lastModified: new Date(Date.now() - 15000000).toISOString() },
      { id: 'BED-WRD-102', name: 'Ward Bed 101-B', type: 'BED_WARD', department: 'Cardiology Ward', status: 'AVAILABLE', version: 6, lastModified: new Date(Date.now() - 20000000).toISOString() },
      { id: 'BED-WRD-103', name: 'Ward Bed 102-A', type: 'BED_WARD', department: 'Orthopedics Ward', status: 'OCCUPIED', version: 8, assignedPatientId: 'PAT-1006', assignedPatientName: 'Robert Lang', lastModified: new Date(Date.now() - 18000000).toISOString() },
      { id: 'BED-WRD-104', name: 'Ward Bed 102-B', type: 'BED_WARD', department: 'Orthopedics Ward', status: 'AVAILABLE', version: 4, lastModified: new Date(Date.now() - 22000000).toISOString() },
      { id: 'BED-WRD-105', name: 'Ward Bed 103-A', type: 'BED_WARD', department: 'Neurology Ward', status: 'AVAILABLE', version: 7, lastModified: new Date(Date.now() - 11000000).toISOString() },
      { id: 'BED-WRD-106', name: 'Ward Bed 103-B', type: 'BED_WARD', department: 'Neurology Ward', status: 'OCCUPIED', version: 10, assignedPatientId: 'PAT-1008', assignedPatientName: 'Amara Okafor', lastModified: new Date(Date.now() - 14000000).toISOString() },
      { id: 'BED-WRD-107', name: 'Ward Bed 104-A', type: 'BED_WARD', department: 'Oncology Ward', status: 'AVAILABLE', version: 5, lastModified: new Date(Date.now() - 30000000).toISOString() },
      { id: 'BED-WRD-108', name: 'Ward Bed 104-B', type: 'BED_WARD', department: 'Oncology Ward', status: 'AVAILABLE', version: 3, lastModified: new Date(Date.now() - 35000000).toISOString() },

      // Operation Theatres
      { id: 'OR-THEATRE-01', name: 'OR Suite 01 (Hybrid Cardiac)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'OCCUPIED', version: 41, assignedPatientId: 'PAT-1002', assignedPatientName: 'Emma Watson-Clarke', lastModified: new Date(Date.now() - 1200000).toISOString(), specs: { cArm: 'Artis pheno Robotic', bypass: 'Maquet HL 20' } },
      { id: 'OR-THEATRE-02', name: 'OR Suite 02 (Neuro-Navigation)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'AVAILABLE', version: 22, lastModified: new Date(Date.now() - 4500000).toISOString(), specs: { scope: 'Zeiss Kinevo 900', nav: 'Medtronic StealthStation' } },
      { id: 'OR-THEATRE-03', name: 'OR Suite 03 (Robotic DaVinci)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'AVAILABLE', version: 19, lastModified: new Date(Date.now() - 6000000).toISOString(), specs: { robot: 'da Vinci Xi Dual Console' } },
      { id: 'OR-THEATRE-04', name: 'OR Suite 04 (Trauma & Ortho)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'AVAILABLE', version: 35, lastModified: new Date(Date.now() - 8500000).toISOString() },
      { id: 'OR-THEATRE-05', name: 'OR Suite 05 (General & Laparoscopic)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'AVAILABLE', version: 14, lastModified: new Date(Date.now() - 9000000).toISOString() },
      { id: 'OR-THEATRE-06', name: 'OR Suite 06 (Emergency Spillover)', type: 'OPERATION_ROOM', department: 'Surgery', status: 'AVAILABLE', version: 10, lastModified: new Date(Date.now() - 10000000).toISOString() },

      // Critical Equipment
      { id: 'EQ-VENT-01', name: 'Hamilton-G5 High-End Ventilator', type: 'EQUIPMENT', department: 'Respiratory', status: 'OCCUPIED', version: 18, assignedPatientId: 'PAT-1001', assignedPatientName: 'Johnathan Miller', lastModified: new Date(Date.now() - 3600000).toISOString(), specs: { mode: 'ASV + INTELLiVENT' } },
      { id: 'EQ-VENT-02', name: 'Getinge Servo-u Ventilator', type: 'EQUIPMENT', department: 'Respiratory', status: 'AVAILABLE', version: 12, lastModified: new Date(Date.now() - 5000000).toISOString(), specs: { mode: 'NAVA + APRV' } },
      { id: 'EQ-VENT-03', name: 'Puritan Bennett 980', type: 'EQUIPMENT', department: 'Respiratory', status: 'AVAILABLE', version: 9, lastModified: new Date(Date.now() - 9000000).toISOString() },
      { id: 'EQ-ECMO-01', name: 'Cardiohelp Mobile ECMO System', type: 'EQUIPMENT', department: 'Cardiology', status: 'AVAILABLE', version: 25, lastModified: new Date(Date.now() - 4000000).toISOString(), specs: { flow: '0.5 - 7.0 L/min VA/VV' } },
      { id: 'EQ-ECMO-02', name: 'Getinge Rotaflow II ECMO', type: 'EQUIPMENT', department: 'Cardiology', status: 'AVAILABLE', version: 14, lastModified: new Date(Date.now() - 11000000).toISOString() },
      { id: 'EQ-DIAL-01', name: 'Prismaflex CRRT Dialysis Machine', type: 'EQUIPMENT', department: 'Nephrology', status: 'AVAILABLE', version: 16, lastModified: new Date(Date.now() - 7000000).toISOString() },
      { id: 'EQ-DIAL-02', name: 'Fresenius multiFiltratePRO', type: 'EQUIPMENT', department: 'Nephrology', status: 'AVAILABLE', version: 8, lastModified: new Date(Date.now() - 15000000).toISOString() },
      { id: 'EQ-MRI-01', name: 'Siemens MAGNETOM 3T MRI', type: 'EQUIPMENT', department: 'Radiology', status: 'AVAILABLE', version: 30, lastModified: new Date(Date.now() - 3000000).toISOString() },
      { id: 'EQ-CT-01', name: 'GE Revolution 256-Slice CT', type: 'EQUIPMENT', department: 'Radiology', status: 'OCCUPIED', version: 27, assignedPatientId: 'PAT-1003', assignedPatientName: 'Derrick Vance', lastModified: new Date(Date.now() - 400000).toISOString() },
      { id: 'EQ-PUMP-01', name: 'Alaris Quad Infusion Array #1', type: 'EQUIPMENT', department: 'ICU', status: 'OCCUPIED', version: 11, assignedPatientId: 'PAT-1001', assignedPatientName: 'Johnathan Miller', lastModified: new Date(Date.now() - 3600000).toISOString() },
      { id: 'EQ-PUMP-02', name: 'Alaris Quad Infusion Array #2', type: 'EQUIPMENT', department: 'ICU', status: 'AVAILABLE', version: 9, lastModified: new Date(Date.now() - 8000000).toISOString() },
    ];

    resourcesList.forEach((res) => this.resources.set(res.id, res));

    // 20+ Patients
    const patientsList: Patient[] = [
      {
        id: 'PAT-1001',
        name: 'Johnathan Miller',
        age: 58,
        gender: 'M',
        severity: 'CRITICAL',
        department: 'ICU',
        assignedDoctorId: 'DOC-001',
        assignedDoctorName: 'Dr. Sarah Williams',
        assignedBedId: 'BED-ICU-01',
        roomNumber: 'ICU Room 01',
        treatmentStatus: 'Mechanical Ventilation & Continuous Hemodynamic Monitoring',
        diagnosis: 'Acute Respiratory Distress Syndrome (ARDS) secondary to Severe Viral Pneumonia',
        medicalHistory: ['Hypertension (12 yrs)', 'Type 2 Diabetes', 'Previous Coronary Stent (2021)'],
        allergies: ['Penicillin', 'Sulfa Drugs'],
        vitals: { heartRate: 98, bloodPressure: '135/84', oxygenLevel: 94, temperature: 38.4, respiratoryRate: 22, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-1', name: 'Norepinephrine Infusion', dosage: '0.08 mcg/kg/min', frequency: 'Continuous IV', nextDose: 'Active Continuous', status: 'ADMINISTERED', prescribedBy: 'Dr. Sarah Williams' },
          { id: 'MED-2', name: 'Meropenem IV', dosage: '1.0 g', frequency: 'Every 8 hours', nextDose: 'Today, 22:00', status: 'SCHEDULED', prescribedBy: 'Dr. Sarah Williams' },
          { id: 'MED-3', name: 'Enoxaparin Sodium', dosage: '40 mg', frequency: 'Once daily SubQ', nextDose: 'Tomorrow, 08:00', status: 'SCHEDULED', prescribedBy: 'Dr. Sarah Williams' },
        ],
        reports: [
          { id: 'REP-01', title: 'Arterial Blood Gas (ABG)', date: 'Today, 14:30', status: 'REVIEWED', summary: 'pH 7.34, PaO2 78 mmHg on FiO2 45%, PaCO2 48 mmHg. Moderate hypercapnic acidosis improving.', criticalFlag: true },
          { id: 'REP-02', title: 'High-Resolution Chest CT', date: 'Yesterday, 19:10', status: 'COMPLETED', summary: 'Bilateral diffuse ground-glass opacities with dependent consolidation consistent with moderate ARDS.' },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Hospital Admission Completed', status: 'COMPLETED', timestamp: 'Aug 23, 08:30 AM', details: 'Admitted via Emergency Trauma Team' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Critical Care Specialist Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 08:45 AM', details: 'Dr. Sarah Williams designated primary intensivist' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Negative Pressure ICU Bed Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 09:10 AM', details: 'BED-ICU-01 allocated with high-flow oxygen' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Blood Work & CT Scans Complete', status: 'COMPLETED', timestamp: 'Aug 23, 11:20 AM', details: 'Chest CT and full metabolic panel performed' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Active ICU Treatment & Ventilation', status: 'IN_PROGRESS', timestamp: 'Aug 24, Present', details: 'Lung protective ventilation mode active' },
          { id: 'J-6', label: 'Weaning & Recovery', friendlyLabel: 'Recovery & Extubation Plan', status: 'PENDING', details: 'Scheduled upon PaO2 stabilization above 85' },
          { id: 'J-7', label: 'Discharge / Step Down', friendlyLabel: 'Step Down to General Ward', status: 'PENDING', details: 'Cardiology Ward Step Down pending' },
        ],
        assignedResources: ['BED-ICU-01', 'EQ-VENT-01', 'EQ-PUMP-01'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1002',
        name: 'Emma Watson-Clarke',
        age: 64,
        gender: 'F',
        severity: 'CRITICAL',
        department: 'Cardiothoracic Surgery',
        assignedDoctorId: 'DOC-002',
        assignedDoctorName: 'Dr. Marcus Vance',
        assignedBedId: 'BED-ICU-03',
        roomNumber: 'Cardiac ICU Suite 03',
        treatmentStatus: 'Undergoing Emergent Coronary Artery Bypass Graft (CABG)',
        diagnosis: 'Triple Vessel Coronary Artery Disease with Acute Anterior STEMI',
        medicalHistory: ['Dyslipidemia', 'Former Smoker (30 pack-yrs)'],
        allergies: ['Aspirin (Bronchospasm)'],
        vitals: { heartRate: 82, bloodPressure: '118/72', oxygenLevel: 98, temperature: 36.8, respiratoryRate: 16, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-4', name: 'Heparin Sodium IV', dosage: '25,000 Units', frequency: 'Continuous Intra-op', nextDose: 'Active', status: 'ADMINISTERED', prescribedBy: 'Dr. Marcus Vance' },
        ],
        reports: [
          { id: 'REP-03', title: 'Emergency Coronary Angiogram', date: 'Today, 11:00', status: 'REVIEWED', summary: '95% occlusion of Proximal LAD, 85% RCA, 80% Circumflex. Urgent surgical revascularization required.', criticalFlag: true },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Hospital Admission Completed', status: 'COMPLETED', timestamp: 'Today, 10:15 AM' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Cardiothoracic Surgeon Assigned', status: 'COMPLETED', timestamp: 'Today, 10:20 AM' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Cardiac ICU Reserved', status: 'COMPLETED', timestamp: 'Today, 10:30 AM' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Angiography Complete', status: 'COMPLETED', timestamp: 'Today, 11:45 AM' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Surgical Revascularization Active', status: 'IN_PROGRESS', timestamp: 'Today, 12:30 PM' },
          { id: 'J-6', label: 'Weaning & Recovery', friendlyLabel: 'Post-Op Cardiac Monitoring', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Cardiac Rehab & Discharge', status: 'PENDING' },
        ],
        assignedResources: ['BED-ICU-03', 'OR-THEATRE-01'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1003',
        name: 'Derrick Vance',
        age: 31,
        gender: 'M',
        severity: 'CRITICAL',
        department: 'Emergency Trauma',
        assignedDoctorId: 'DOC-003',
        assignedDoctorName: 'Dr. Elena Rostova',
        assignedBedId: 'BED-ER-01',
        roomNumber: 'Trauma Bay 01',
        treatmentStatus: 'Emergency Polytrauma Resuscitation & Diagnostic Imaging',
        diagnosis: 'High-Velocity Motor Vehicle Collision, Hemoperitoneum & Pelvic Fracture',
        medicalHistory: ['No known significant past history'],
        allergies: ['No Known Drug Allergies (NKDA)'],
        vitals: { heartRate: 124, bloodPressure: '90/58', oxygenLevel: 93, temperature: 36.2, respiratoryRate: 28, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-5', name: 'Tranexamic Acid (TXA)', dosage: '1.0 g IV', frequency: 'STAT Bolus', nextDose: 'Administered', status: 'ADMINISTERED', prescribedBy: 'Dr. Elena Rostova' },
          { id: 'MED-6', name: 'Packed Red Blood Cells (O-Neg)', dosage: '2 Units', frequency: 'Rapid Infuser', nextDose: 'In Progress', status: 'ADMINISTERED', prescribedBy: 'Dr. Elena Rostova' },
        ],
        reports: [
          { id: 'REP-04', title: 'FAST Ultrasound (Bedside)', date: 'Today, 16:15', status: 'REVIEWED', summary: 'Positive fluid in Morrison\'s pouch and splenorenal recess. Immediate CT angiogram scheduled.', criticalFlag: true },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Trauma Code Alpha Activated', status: 'COMPLETED', timestamp: 'Today, 16:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Trauma Team Leader Assigned', status: 'COMPLETED', timestamp: 'Today, 16:02' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Resuscitation Bay Locked', status: 'COMPLETED', timestamp: 'Today, 16:05' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Whole Body CT & FAST Scan', status: 'IN_PROGRESS', timestamp: 'Today, 16:15' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Massive Transfusion Protocol', status: 'PENDING' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Surgical ICU Transfer', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Rehab Evaluation', status: 'PENDING' },
        ],
        assignedResources: ['BED-ER-01', 'EQ-CT-01'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1004',
        name: 'Carlos Ramirez',
        age: 49,
        gender: 'M',
        severity: 'HIGH',
        department: 'Neurology / Stroke Care',
        assignedDoctorId: 'DOC-004',
        assignedDoctorName: 'Dr. Arthur Chen',
        assignedBedId: 'BED-ICU-05',
        roomNumber: 'ICU Room 05',
        treatmentStatus: 'Post-Mechanical Thrombectomy Monitoring',
        diagnosis: 'Acute Ischemic Stroke (Right Middle Cerebral Artery M1 segment)',
        medicalHistory: ['Atrial Fibrillation', 'Hypercholesterolemia'],
        allergies: ['Contrast Dye (Mild rash)'],
        vitals: { heartRate: 76, bloodPressure: '142/86', oxygenLevel: 97, temperature: 37.1, respiratoryRate: 18, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-7', name: 'Nicardipine Infusion', dosage: '5.0 mg/hr', frequency: 'Titrated IV', nextDose: 'Active', status: 'ADMINISTERED', prescribedBy: 'Dr. Arthur Chen' },
        ],
        reports: [
          { id: 'REP-05', title: 'Post-Op Brain MRI', date: 'Today, 13:00', status: 'COMPLETED', summary: 'TICI 3 complete recanalization of Right MCA. Minimal core infarct volume, penumbra salvaged.' },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Stroke Protocol Admission', status: 'COMPLETED', timestamp: 'Today, 09:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Neurocritical Care Doctor Assigned', status: 'COMPLETED', timestamp: 'Today, 09:10' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Neuro ICU Bed Assigned', status: 'COMPLETED', timestamp: 'Today, 09:20' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Angiography & Perfusion CT', status: 'COMPLETED', timestamp: 'Today, 10:00' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Thrombectomy Completed & Monitoring', status: 'IN_PROGRESS', timestamp: 'Today, 11:30' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Neuro Rehabilitation Protocol', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Outpatient Follow-up Scheduled', status: 'PENDING' },
        ],
        assignedResources: ['BED-ICU-05'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1005',
        name: 'Mei-Ling Zhang',
        age: 72,
        gender: 'F',
        severity: 'MEDIUM',
        department: 'Cardiology Ward',
        assignedDoctorId: 'DOC-001',
        assignedDoctorName: 'Dr. Sarah Williams',
        assignedBedId: 'BED-WRD-101',
        roomNumber: 'Ward 101-A',
        treatmentStatus: 'IV Diuresis and Guideline-Directed Medical Therapy',
        diagnosis: 'Congestive Heart Failure Exacerbation (NYHA Class III)',
        medicalHistory: ['Chronic Kidney Disease Stage 3', 'Ischemic Cardiomyopathy (EF 30%)'],
        allergies: ['Morphine (Nausea/Vomiting)'],
        vitals: { heartRate: 70, bloodPressure: '128/78', oxygenLevel: 96, temperature: 36.7, respiratoryRate: 16, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-8', name: 'Furosemide IV', dosage: '40 mg', frequency: 'Twice daily', nextDose: 'Today, 20:00', status: 'SCHEDULED', prescribedBy: 'Dr. Sarah Williams' },
          { id: 'MED-9', name: 'Sacubitril/Valsartan', dosage: '24/26 mg', frequency: 'Twice daily', nextDose: 'Tomorrow, 08:00', status: 'SCHEDULED', prescribedBy: 'Dr. Sarah Williams' },
        ],
        reports: [
          { id: 'REP-06', title: 'Transthoracic Echocardiogram', date: 'Yesterday, 14:00', status: 'REVIEWED', summary: 'Global LV hypokinesis, EF 32%, moderate mitral regurgitation, elevated filling pressures.' },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Direct Ward Admission', status: 'COMPLETED', timestamp: 'Aug 22, 11:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Cardiologist Assigned', status: 'COMPLETED', timestamp: 'Aug 22, 11:30' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Telemetry Ward Bed Assigned', status: 'COMPLETED', timestamp: 'Aug 22, 12:00' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Echo & BNP Biomarkers Done', status: 'COMPLETED', timestamp: 'Aug 23, 09:00' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Diuresis & Medication Optimization', status: 'IN_PROGRESS', timestamp: 'Aug 24, Present' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Functional Ambulation Test', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Discharge Planning', status: 'PENDING' },
        ],
        assignedResources: ['BED-WRD-101'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1006',
        name: 'Robert Lang',
        age: 45,
        gender: 'M',
        severity: 'STABLE',
        department: 'Orthopedics Ward',
        assignedDoctorId: 'DOC-006',
        assignedDoctorName: 'Dr. James Thornton',
        assignedBedId: 'BED-WRD-103',
        roomNumber: 'Ward 102-A',
        treatmentStatus: 'Post-Operative Physical Therapy & Wound Care',
        diagnosis: 'Closed Bimalleolar Right Ankle Fracture Status-Post ORIF',
        medicalHistory: ['Seasonal Allergic Rhinitis'],
        allergies: ['NKDA'],
        vitals: { heartRate: 74, bloodPressure: '122/78', oxygenLevel: 99, temperature: 36.6, respiratoryRate: 14, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-10', name: 'Acetaminophen / Codeine', dosage: '500/30 mg', frequency: 'Every 6 hrs PRN', nextDose: 'As needed', status: 'SCHEDULED', prescribedBy: 'Dr. James Thornton' },
          { id: 'MED-11', name: 'Cefazolin IV', dosage: '1.0 g', frequency: 'Every 8 hours', nextDose: 'Today, 23:00', status: 'SCHEDULED', prescribedBy: 'Dr. James Thornton' },
        ],
        reports: [
          { id: 'REP-07', title: 'Post-Op Ankle X-Ray Series', date: 'Today, 08:30', status: 'REVIEWED', summary: 'Anatomical reduction of medial and lateral malleoli with rigid screw/plate fixation in place.' },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Surgical Admission', status: 'COMPLETED', timestamp: 'Aug 23, 07:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Orthopedic Surgeon Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 07:15' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Surgical Bed Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 07:30' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Pre-Op Clearance Completed', status: 'COMPLETED', timestamp: 'Aug 23, 09:00' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Surgery Succeeded & Recovery', status: 'IN_PROGRESS', timestamp: 'Aug 24, Present' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Weight-bearing Physical Therapy', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Home Discharge Anticipated Tomorrow', status: 'PENDING' },
        ],
        assignedResources: ['BED-WRD-103'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1007',
        name: 'Sarah Jenkins',
        age: 26,
        gender: 'F',
        severity: 'HIGH',
        department: 'Emergency',
        assignedDoctorId: 'DOC-003',
        assignedDoctorName: 'Dr. Elena Rostova',
        assignedBedId: 'BED-ER-04',
        roomNumber: 'Emergency Bay 04',
        treatmentStatus: 'Continuous Nebulization & IV Steroid Therapy',
        diagnosis: 'Status Asthmaticus (Severe Acute Exacerbation)',
        medicalHistory: ['Brittle Asthma', 'Atopic Dermatitis'],
        allergies: ['NSAIDs / Ibuprofen (Severe Wheezing)'],
        vitals: { heartRate: 112, bloodPressure: '116/74', oxygenLevel: 92, temperature: 37.0, respiratoryRate: 26, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-12', name: 'Albuterol + Ipratropium Nebs', dosage: '2.5 / 0.5 mg', frequency: 'Continuous 1 hr', nextDose: 'Active', status: 'ADMINISTERED', prescribedBy: 'Dr. Elena Rostova' },
          { id: 'MED-13', name: 'Methylprednisolone IV', dosage: '125 mg', frequency: 'STAT Bolus', nextDose: 'Given', status: 'ADMINISTERED', prescribedBy: 'Dr. Elena Rostova' },
        ],
        reports: [
          { id: 'REP-08', title: 'Chest Radiograph (AP portable)', date: 'Today, 17:00', status: 'REVIEWED', summary: 'Hyperinflation with flattened diaphragms, no focal consolidations or pneumothorax.' },
        ],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Urgent ER Triage', status: 'COMPLETED', timestamp: 'Today, 16:45' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Emergency Specialist Assigned', status: 'COMPLETED', timestamp: 'Today, 16:48' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Emergency Bay 04 Assigned', status: 'COMPLETED', timestamp: 'Today, 16:50' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'Blood Gases & Peak Flow Test', status: 'COMPLETED', timestamp: 'Today, 17:05' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Aggressive Bronchodilator Therapy', status: 'IN_PROGRESS', timestamp: 'Today, 17:15' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Stepdown to Observation', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Discharge with Inhaler Regimen', status: 'PENDING' },
        ],
        assignedResources: ['BED-ER-04'],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1008',
        name: 'Amara Okafor',
        age: 52,
        gender: 'F',
        severity: 'MEDIUM',
        department: 'Neurology Ward',
        assignedDoctorId: 'DOC-004',
        assignedDoctorName: 'Dr. Arthur Chen',
        assignedBedId: 'BED-WRD-106',
        roomNumber: 'Ward 103-B',
        treatmentStatus: 'Video EEG Monitoring and Antiepileptic Titration',
        diagnosis: 'Intractable Temporal Lobe Epilepsy & Complex Partial Seizures',
        medicalHistory: ['Prior viral encephalitis (2018)'],
        allergies: ['Levetiracetam (Severe agitation)'],
        vitals: { heartRate: 72, bloodPressure: '120/80', oxygenLevel: 98, temperature: 36.9, respiratoryRate: 15, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-14', name: 'Lacosamide IV', dosage: '200 mg', frequency: 'Twice daily', nextDose: 'Today, 21:00', status: 'SCHEDULED', prescribedBy: 'Dr. Arthur Chen' },
          { id: 'MED-15', name: 'Clobazam', dosage: '10 mg', frequency: 'At bedtime', nextDose: 'Today, 22:00', status: 'SCHEDULED', prescribedBy: 'Dr. Arthur Chen' },
        ],
        reports: [
          { id: 'REP-09', title: '24-Hour Continuous Video-EEG', date: 'Today, 15:00', status: 'REVIEWED', summary: 'Frequent epileptiform sharp waves in left anterior temporal leads; captured 2 subclinical focal events.' },
        ],
        journey: [
          { id: 'J-1', label: 'Admission', friendlyLabel: 'Elective Neuro Monitoring Admission', status: 'COMPLETED', timestamp: 'Aug 23, 10:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Epileptologist Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 10:15' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'EEG Telemetry Bed Assigned', status: 'COMPLETED', timestamp: 'Aug 23, 10:30' },
          { id: 'J-4', label: 'Diagnostic Testing', friendlyLabel: 'High Density EEG Active', status: 'COMPLETED', timestamp: 'Aug 23, 12:00' },
          { id: 'J-5', label: 'Treatment in Progress', friendlyLabel: 'Medication Optimization', status: 'IN_PROGRESS', timestamp: 'Aug 24, Present' },
          { id: 'J-6', label: 'Recovery', friendlyLabel: 'Seizure Free Observation (48h)', status: 'PENDING' },
          { id: 'J-7', label: 'Discharge', friendlyLabel: 'Discharge with Updated Prescription', status: 'PENDING' },
        ],
        assignedResources: ['BED-WRD-106'],
        lastUpdated: new Date().toISOString(),
      },
      // Additional Patients 1009 - 1022 to reach 22 patients
      {
        id: 'PAT-1009',
        name: 'Liam Gallagher',
        age: 39,
        gender: 'M',
        severity: 'STABLE',
        department: 'Internal Medicine',
        assignedDoctorId: 'DOC-010',
        assignedDoctorName: 'Dr. David Kim',
        treatmentStatus: 'Awaiting Diagnostic Colonoscopy',
        diagnosis: 'Unexplained Lower GI Bleed & Moderate Iron Deficiency Anemia',
        medicalHistory: ['GERD'],
        allergies: ['NKDA'],
        vitals: { heartRate: 78, bloodPressure: '115/72', oxygenLevel: 98, temperature: 36.8, respiratoryRate: 14, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-16', name: 'Ferric Carboxymaltose IV', dosage: '500 mg', frequency: 'Single infusion', nextDose: 'Completed', status: 'ADMINISTERED', prescribedBy: 'Dr. David Kim' }],
        reports: [{ id: 'REP-10', title: 'Complete Blood Count (CBC)', date: 'Today, 09:00', status: 'REVIEWED', summary: 'Hemoglobin 9.4 g/dL, MCV 74 fL (Microcytic anemia).' }],
        journey: [
          { id: 'J-1', label: 'Admission', friendlyLabel: 'Medical Ward Admission', status: 'COMPLETED', timestamp: 'Today, 08:30' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Internist Assigned', status: 'COMPLETED', timestamp: 'Today, 08:45' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Awaiting Ward Bed', status: 'IN_PROGRESS', details: 'Allocation transaction queued' },
          { id: 'J-4', label: 'Diagnostics', friendlyLabel: 'Endoscopy Scheduled', status: 'PENDING' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1010',
        name: 'Fatima Al-Mansoor',
        age: 61,
        gender: 'F',
        severity: 'HIGH',
        department: 'Renal Care',
        assignedDoctorId: 'DOC-005',
        assignedDoctorName: 'Dr. Priyanka Sharma',
        treatmentStatus: 'Urgent Hemodialysis for Severe Hyperkalemia',
        diagnosis: 'End-Stage Renal Disease with Missing Dialysis Access Clotting',
        medicalHistory: ['ESRD on HD (4 yrs)', 'Hypertension'],
        allergies: ['Latex'],
        vitals: { heartRate: 88, bloodPressure: '168/98', oxygenLevel: 96, temperature: 37.0, respiratoryRate: 18, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-17', name: 'Calcium Gluconate 10% IV', dosage: '1.0 g', frequency: 'STAT Push', nextDose: 'Given', status: 'ADMINISTERED', prescribedBy: 'Dr. Priyanka Sharma' }],
        reports: [{ id: 'REP-11', title: 'Emergency Serum Chemistry', date: 'Today, 15:45', status: 'REVIEWED', summary: 'Potassium 6.9 mEq/L (CRITICAL HIGH), Creatinine 8.2 mg/dL.', criticalFlag: true }],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Emergency Arrival', status: 'COMPLETED', timestamp: 'Today, 15:30' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Nephrologist Assigned', status: 'COMPLETED', timestamp: 'Today, 15:35' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Dialysis Suite Request Pending', status: 'IN_PROGRESS' },
          { id: 'J-4', label: 'Treatment in Progress', friendlyLabel: 'Emergent Hemodialysis Active', status: 'PENDING' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1011',
        name: 'Samuel O\'Connor',
        age: 48,
        gender: 'M',
        severity: 'MEDIUM',
        department: 'Surgery',
        assignedDoctorId: 'DOC-002',
        assignedDoctorName: 'Dr. Marcus Vance',
        treatmentStatus: 'Pre-operative Evaluation for Cholecystectomy',
        diagnosis: 'Acute Calculous Cholecystitis',
        medicalHistory: ['Hyperlipidemia'],
        allergies: ['Ciprofloxacin'],
        vitals: { heartRate: 80, bloodPressure: '130/82', oxygenLevel: 98, temperature: 37.8, respiratoryRate: 16, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-18', name: 'Piperacillin / Tazobactam', dosage: '3.375 g IV', frequency: 'Every 6 hrs', nextDose: 'Today, 21:30', status: 'SCHEDULED', prescribedBy: 'Dr. Marcus Vance' }],
        reports: [{ id: 'REP-12', title: 'Abdominal Ultrasound', date: 'Today, 11:30', status: 'REVIEWED', summary: 'Gallbladder wall thickening 5.5mm, pericholecystic fluid, multiple gallstones.' }],
        journey: [
          { id: 'J-1', label: 'Admission', friendlyLabel: 'Surgical Admission', status: 'COMPLETED', timestamp: 'Today, 10:00' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'General Surgeon Assigned', status: 'COMPLETED', timestamp: 'Today, 10:15' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'Surgical Prep Unit', status: 'COMPLETED', timestamp: 'Today, 10:45' },
          { id: 'J-4', label: 'Surgery Scheduled', friendlyLabel: 'OR Suite Scheduling Pending', status: 'IN_PROGRESS' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1012',
        name: 'Jessica Taylor',
        age: 8,
        gender: 'F',
        severity: 'HIGH',
        department: 'Pediatrics',
        assignedDoctorId: 'DOC-007',
        assignedDoctorName: 'Dr. Sofia Rodriguez',
        treatmentStatus: 'PICU Monitoring for Diabetic Ketoacidosis (DKA)',
        diagnosis: 'New-Onset Type 1 Diabetes Mellitus Presenting with Severe DKA',
        medicalHistory: ['No prior chronic illness'],
        allergies: ['NKDA'],
        vitals: { heartRate: 118, bloodPressure: '102/64', oxygenLevel: 99, temperature: 37.2, respiratoryRate: 24, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-19', name: 'Regular Insulin IV Infusion', dosage: '0.05 Units/kg/hr', frequency: 'Continuous', nextDose: 'Active', status: 'ADMINISTERED', prescribedBy: 'Dr. Sofia Rodriguez' }],
        reports: [{ id: 'REP-13', title: 'Venous Blood Gas + Ketones', date: 'Today, 14:00', status: 'REVIEWED', summary: 'pH 7.18, HCO3 9 mmol/L, Blood Glucose 480 mg/dL, Beta-hydroxybutyrate 5.8 mmol/L.', criticalFlag: true }],
        journey: [
          { id: 'J-1', label: 'Emergency Admission', friendlyLabel: 'Pediatric Emergency Arrival', status: 'COMPLETED', timestamp: 'Today, 13:30' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'PICU Intensivist Assigned', status: 'COMPLETED', timestamp: 'Today, 13:40' },
          { id: 'J-3', label: 'Bed Allocated', friendlyLabel: 'PICU Bed Requesting', status: 'IN_PROGRESS' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1013',
        name: 'Hannah Brooks',
        age: 34,
        gender: 'F',
        severity: 'STABLE',
        department: 'Oncology',
        assignedDoctorId: 'DOC-009',
        assignedDoctorName: 'Dr. Maya Patel',
        treatmentStatus: 'Cycle 3 AC Chemotherapy Infusion',
        diagnosis: 'Invasive Ductal Carcinoma Breast (Stage IIA, ER+/PR+/HER2-)',
        medicalHistory: ['Prior Appendectomy'],
        allergies: ['NKDA'],
        vitals: { heartRate: 68, bloodPressure: '118/76', oxygenLevel: 99, temperature: 36.6, respiratoryRate: 14, lastUpdated: new Date().toISOString() },
        medications: [
          { id: 'MED-20', name: 'Ondansetron IV', dosage: '8 mg', frequency: 'Pre-chemo IV', nextDose: 'Given', status: 'ADMINISTERED', prescribedBy: 'Dr. Maya Patel' },
          { id: 'MED-21', name: 'Doxorubicin + Cyclophosphamide', dosage: '60/600 mg/m2', frequency: 'Cycle 3', nextDose: 'In Progress', status: 'ADMINISTERED', prescribedBy: 'Dr. Maya Patel' },
        ],
        reports: [{ id: 'REP-14', title: 'Pre-Chemo Labs (ANC / Platelets)', date: 'Today, 08:00', status: 'REVIEWED', summary: 'ANC 2,400/mcL, Platelets 210,000/mcL. Clearance granted for Cycle 3.' }],
        journey: [
          { id: 'J-1', label: 'Admission', friendlyLabel: 'Oncology Day Care Admission', status: 'COMPLETED', timestamp: 'Today, 08:30' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'Medical Oncologist Assigned', status: 'COMPLETED', timestamp: 'Today, 08:45' },
          { id: 'J-3', label: 'Infusion in Progress', friendlyLabel: 'Infusion Therapy Running', status: 'IN_PROGRESS', timestamp: 'Today, 09:30' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1014',
        name: 'Victor Kovalev',
        age: 67,
        gender: 'M',
        severity: 'CRITICAL',
        department: 'Cardiology',
        assignedDoctorId: 'DOC-002',
        assignedDoctorName: 'Dr. Marcus Vance',
        treatmentStatus: 'Cardiogenic Shock Requiring Veno-Arterial ECMO Cannulation',
        diagnosis: 'Acute Massive Myocardial Infarction with Refractory Cardiogenic Shock',
        medicalHistory: ['Prior CABG (2015)', 'Severe Peripheral Vascular Disease'],
        allergies: ['Penicillin', 'Codeine'],
        vitals: { heartRate: 110, bloodPressure: '82/48', oxygenLevel: 90, temperature: 35.9, respiratoryRate: 28, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-22', name: 'Epinephrine Infusion', dosage: '0.1 mcg/kg/min', frequency: 'Continuous', nextDose: 'Active', status: 'ADMINISTERED', prescribedBy: 'Dr. Marcus Vance' }],
        reports: [{ id: 'REP-15', title: 'Lactate & Cardiac Output Profiling', date: 'Today, 16:30', status: 'REVIEWED', summary: 'Lactate 5.4 mmol/L (ELEVATED), Cardiac Index 1.4 L/min/m2. Urgent ECMO support indicated.', criticalFlag: true }],
        journey: [
          { id: 'J-1', label: 'Emergency Code Blue', friendlyLabel: 'Emergency Cardiac Alert', status: 'COMPLETED', timestamp: 'Today, 16:15' },
          { id: 'J-2', label: 'Doctor Assigned', friendlyLabel: 'ECMO Surgical Team Assembled', status: 'COMPLETED', timestamp: 'Today, 16:20' },
          { id: 'J-3', label: 'Resource Locked', friendlyLabel: 'ECMO Machine & Hybrid OR Requested', status: 'IN_PROGRESS', timestamp: 'Today, 16:35' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'PAT-1015',
        name: 'Grace Hopper-Diaz',
        age: 50,
        gender: 'F',
        severity: 'STABLE',
        department: 'Internal Medicine',
        assignedDoctorId: 'DOC-010',
        assignedDoctorName: 'Dr. David Kim',
        treatmentStatus: 'Completing IV Antibiotic Course for Pyelonephritis',
        diagnosis: 'Complicated Pyelonephritis (E. coli ESBL-negative)',
        medicalHistory: ['Nephrolithiasis'],
        allergies: ['Sulfa'],
        vitals: { heartRate: 72, bloodPressure: '124/76', oxygenLevel: 98, temperature: 36.8, respiratoryRate: 15, lastUpdated: new Date().toISOString() },
        medications: [{ id: 'MED-23', name: 'Ceftriaxone IV', dosage: '2.0 g', frequency: 'Once daily', nextDose: 'Tomorrow, 10:00', status: 'SCHEDULED', prescribedBy: 'Dr. David Kim' }],
        reports: [{ id: 'REP-16', title: 'Repeat Urine & Blood Cultures', date: 'Today, 09:30', status: 'COMPLETED', summary: 'Cultures sterile at 48 hours. Clinical cure achieved.' }],
        journey: [
          { id: 'J-1', label: 'Admission', friendlyLabel: 'Admission Completed', status: 'COMPLETED', timestamp: 'Aug 21, 14:00' },
          { id: 'J-2', label: 'Treatment', friendlyLabel: 'IV Antibiotics Administered', status: 'COMPLETED', timestamp: 'Aug 24, 09:00' },
          { id: 'J-3', label: 'Discharge', friendlyLabel: 'Discharge Planning Ready', status: 'IN_PROGRESS' },
        ],
        assignedResources: [],
        lastUpdated: new Date().toISOString(),
      },
    ];

    patientsList.forEach((pat) => this.patients.set(pat.id, pat));

    // Seed Initial Transactions
    const initialTxns: Transaction[] = [
      {
        id: 'TXN-8472',
        type: 'ALLOCATE_RESOURCE',
        patientId: 'PAT-1001',
        patientName: 'Johnathan Miller',
        doctorId: 'DOC-001',
        doctorName: 'Dr. Sarah Williams',
        resourceId: 'BED-ICU-01',
        resourceName: 'ICU Bed 01 (Negative Pressure)',
        priority: 'CRITICAL',
        status: 'SUCCESS',
        idempotencyKey: 'IDEMP-8472-ALLOC-ICU01',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        completedAt: new Date(Date.now() - 3598000).toISOString(),
        expectedVersion: 13,
        actualVersion: 14,
        currentStepIndex: 5,
        steps: [
          { stepIndex: 1, name: 'Validate Patient & Clinical Record', status: 'SUCCESS', timestamp: new Date(Date.now() - 3600000).toISOString() },
          { stepIndex: 2, name: 'Check Resource Availability & State', status: 'SUCCESS', timestamp: new Date(Date.now() - 3599500).toISOString() },
          { stepIndex: 3, name: 'Acquire Distributed Resource Lock', status: 'SUCCESS', timestamp: new Date(Date.now() - 3599000).toISOString() },
          { stepIndex: 4, name: 'Execute Optimistic Version Increment (v13 -> v14)', status: 'SUCCESS', timestamp: new Date(Date.now() - 3598500).toISOString() },
          { stepIndex: 5, name: 'Commit Resource Allocation & Emit Notifications', status: 'SUCCESS', timestamp: new Date(Date.now() - 3598000).toISOString() },
        ],
      },
      {
        id: 'TXN-8473',
        type: 'RESERVE_RESOURCE',
        patientId: 'PAT-1002',
        patientName: 'Emma Watson-Clarke',
        doctorId: 'DOC-002',
        doctorName: 'Dr. Marcus Vance',
        resourceId: 'OR-THEATRE-01',
        resourceName: 'OR Suite 01 (Hybrid Cardiac)',
        priority: 'CRITICAL',
        status: 'SUCCESS',
        idempotencyKey: 'IDEMP-8473-OR01-RES',
        createdAt: new Date(Date.now() - 1200000).toISOString(),
        completedAt: new Date(Date.now() - 1198500).toISOString(),
        expectedVersion: 40,
        actualVersion: 41,
        currentStepIndex: 5,
        steps: [
          { stepIndex: 1, name: 'Validate Surgical Order', status: 'SUCCESS' },
          { stepIndex: 2, name: 'Check Theatre Sterilization & Availability', status: 'SUCCESS' },
          { stepIndex: 3, name: 'Acquire Lock on OR Suite 01', status: 'SUCCESS' },
          { stepIndex: 4, name: 'Increment Resource Version (v40 -> v41)', status: 'SUCCESS' },
          { stepIndex: 5, name: 'Confirm Reservation to Cardiothoracic Service', status: 'SUCCESS' },
        ],
      },
    ];

    initialTxns.forEach((txn) => this.transactions.set(txn.id, txn));

    // Initial Audit Events
    this.auditEvents = [
      {
        id: 'EVT-9001',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        transactionId: 'TXN-8472',
        patientId: 'PAT-1001',
        resourceId: 'BED-ICU-01',
        serviceName: 'Transaction Orchestrator',
        eventType: 'ALLOCATION_REQUESTED',
        previousState: 'AVAILABLE',
        newState: 'LOCKED',
        status: 'INFO',
        idempotencyKey: 'IDEMP-8472-ALLOC-ICU01',
        details: 'Doctor Sarah Williams initiated CRITICAL resource allocation for Johnathan Miller.',
      },
      {
        id: 'EVT-9002',
        timestamp: new Date(Date.now() - 3599000).toISOString(),
        transactionId: 'TXN-8472',
        patientId: 'PAT-1001',
        resourceId: 'BED-ICU-01',
        serviceName: 'Bed Management Service',
        eventType: 'RESOURCE_LOCKED',
        previousState: 'LOCKED',
        newState: 'RESERVED',
        status: 'INFO',
        idempotencyKey: 'IDEMP-8472-ALLOC-ICU01',
        details: 'Optimistic lock acquired on BED-ICU-01 (version verified: 13).',
      },
      {
        id: 'EVT-9003',
        timestamp: new Date(Date.now() - 3598000).toISOString(),
        transactionId: 'TXN-8472',
        patientId: 'PAT-1001',
        resourceId: 'BED-ICU-01',
        serviceName: 'Bed Management Service',
        eventType: 'ALLOCATION_CONFIRMED',
        previousState: 'RESERVED',
        newState: 'OCCUPIED',
        status: 'SUCCESS',
        idempotencyKey: 'IDEMP-8472-ALLOC-ICU01',
        details: 'Resource BED-ICU-01 successfully allocated to patient PAT-1001. Version bumped to 14.',
      },
      {
        id: 'EVT-9004',
        timestamp: new Date(Date.now() - 3597500).toISOString(),
        transactionId: 'TXN-8472',
        patientId: 'PAT-1001',
        serviceName: 'Notification Service',
        eventType: 'PATIENT_NOTIFICATION_DISPATCHED',
        newState: 'DELIVERED',
        status: 'SUCCESS',
        details: 'Patient friendly notification: "Your Negative Pressure ICU Bed has been assigned."',
      },
    ];

    // Seed Notifications
    this.notifications = [
      {
        id: 'NOTIF-01',
        recipientRole: 'DOCTOR',
        recipientId: 'DOC-001',
        title: 'Bed Allocation Confirmed',
        message: 'ICU Bed 01 (Negative Pressure) assigned to Johnathan Miller (PAT-1001).',
        technicalDetails: 'TXN-8472 | Version 14 | Lock released',
        timestamp: new Date(Date.now() - 3597000).toISOString(),
        read: false,
        type: 'SUCCESS',
        relatedTxnId: 'TXN-8472',
      },
      {
        id: 'NOTIF-02',
        recipientRole: 'PATIENT',
        recipientId: 'PAT-1001',
        title: 'Bed Assigned',
        message: 'Your hospital room (ICU Room 01) is ready and assigned to your care team.',
        timestamp: new Date(Date.now() - 3597000).toISOString(),
        read: false,
        type: 'INFO',
      },
      {
        id: 'NOTIF-03',
        recipientRole: 'ADMIN',
        title: 'CRITICAL Allocation Committed',
        message: 'BED-ICU-01 allocated to PAT-1001 by Dr. Sarah Williams (TXN-8472).',
        technicalDetails: 'Latency: 2.0s | OCC: OK',
        timestamp: new Date(Date.now() - 3597000).toISOString(),
        read: false,
        type: 'TRANSACTION',
        relatedTxnId: 'TXN-8472',
      },
    ];
  }
}

export const db = new HospitalDatabase();
